/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package simple.gradle.java.app;

public class App {
    public static int getSum(int num1, int num2) {
        return num1+num2;

    }

    public static void main(String[] args) {
            System.out.println("Sum is " + getSum(18,9));
            System.out.println();
            System.out.println("My name is Sagar Goswami. I am an ambitious DevOps Engineer with experience in AWS, Docker, Jenkins, CI/CD, Ansible, Shell Script, Linux, and Git.");
    }
}
